### ISSUE TITLE
Dynamically populate the command name list

### ISSUE THREAD

**Issue by jayvdb** [hairetdin/django-dmcadmin#3]
The list of available commands can be pre-populated (and cached, or may even be cached in Django somewhere).  I know the `migrate` command has its own logic for finding all management commands, so maybe that logic could be replicated.   https://github.com/vint21h/django-mcadmin appears to determine the command list dynamically in https://github.com/vint21h/django-mcadmin/blob/master/mcadmin/loader.py
However, it only recognises commands decorated with lots of custom attributes, which makes it unusable with most django commands provided by other Django apps.

**Comment by jayvdb** [comment]
https://pypi.org/project/django-chroniker/ has a dynamic dropdown for the list of admin commands.

**Comment by hairetdin** [comment]
It my decision to do static list commands and not choise dinamicaly, because it GUI for users, not for programmers or sysadmin, which can run any command from command line. You can add any command to static list https://github.com/hairetdin/django-dmcadmin/blob/master/dmcadmin/models.py#L75 or write and run it from GUI. But allowing any user any command is not very joyful in the future

**Comment by jayvdb** [comment]
I found another similar tool which has a nice UI with list of commands, but needed a bit of hacking to get it working https://github.com/willandskill/django-executor/pull/1

**Comment by hairetdin** [comment]
In this project there will be only a static list of commands
